### ISSUE TITLE
RegressionTables is not working on v1.0.4

### ISSUE THREAD

**Issue by ethanminfang** [jmboehm/RegressionTables.jl#24]
Hi,

I tried to load RegressionTables in Julia v1.0.4, but the Precompiling incurs an Error. The problem cannot be resolved with either reinstall or restart Julia.

**Comment by jmboehm** [comment]
What is the error message?

**Comment by felixholub** [comment]
Have you tried to run `update` in the package manager? It solved my issues in #25

**Comment by junder873** [comment]
I am also having this issue, even after running update (update now results in no changes). Looking at the issue in #25 it is exactly the same error message.

**Comment by jmboehm** [comment]
Looks like the 0.6 update to `StatsModels` broke it. I'll try to update it in the next few days.

**Comment by ethanminfang** [comment]
> Have you tried to run `update` in the package manager? It solved my issues in #25

I also updated Julia to 1.2.0, that works. 
But in 1.0.4 update does not work just as junder873 said. (I guess some people will stay with 1.0.4 ...)

**Comment by jmboehm** [comment]
#28 is transitioning to StatsModels 0.6 (thereby moving from `DataFrameRegressionModel` to `TableRegressionModel`), but dropping support for julia 1.0 (because FixedEffectModels.jl dropped support for it). If you are on 1.0.x and need to use RegressionTables, I suggest downgrading to StatsModels <0.6. Otherwise, the patch on master should solve it.
