### ISSUE TITLE
Support for Microeconometrics

### ISSUE THREAD

**Issue by lbittarello** [jmboehm/RegressionTables.jl#6]
I was wondering if RegressionTables could support [Microeconometrics](https://github.com/lbittarello/Microeconometrics.jl). I would be happy to help out with the code. How would one go about it?

Thanks!

**Comment by jmboehm** [comment]
Yes, would be great. Ideally, your package would provide a `DataFrameRegressionModel`, like GLM.jl, then `regtable()` should be able to use it. Otherwise, you'd need to change `regtable()` (but I'd prefer the former variant -- otherwise we're duplicating interfaces and `RegressionTables` would be requiring several estimation packages).

**Comment by lbittarello** [comment]
Is it absolutely necessary to provide a `DataFrameRegressionModel`? The current output is a `RegressionModel` (note that `DataFrameRegressionModel` is a subtype of `RegressionModel`). The standard methods are supported (`coef`, `coefnames`, `nobs`, `r2`, etc.). It may not even be necessary to require Microeconometrics.jl as long as RegressionTables.jl provides support for abstract statistical models.

**Comment by jmboehm** [comment]
I'd be happy to work with a `RegressionModel` if it contains all the information we need for the table (notably variable names).

**Comment by lbittarello** [comment]
One can get covariate labels from `coefnames`. I don't think StatsModels.jl provides a method to retrieve the name of the dependent variable though. We could propose it in a pull request – it would be a good addition.

**Comment by jmboehm** [comment]
Closing this as RegressionTables now supports `RegressionModel`s.
